version: "3.6"
services:
  web:
    image: nginx:1.15.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "33342:80"
    volumes:
      # use bind to replace Nginx configuration
      - type: bind
        source: ../nginx/conf.d/react-for-beginners.conf
        target: /etc/nginx/conf.d/default.conf
      # use bind to mount the source directory of the host on the container for development
      - type: bind
        source: ../react-for-beginners
        target: /usr/share/nginx/html
      # - type: volume
      #   source: static
      #   target: /usr/share/nginx/html/static
volumes:
  static:
